name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest  # Use the latest version of Windows as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the latest Node.js version available at the time

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run run-tests
